package kui.cluster.api

import java.time.Instant

import scala.concurrent.duration.*

import cats.data.NonEmptyList
import cats.effect.IO
import cats.effect.kernel.Ref
import cats.syntax.all.*
import fs2.Stream

import kui.cluster.application.*
import kui.cluster.domain.*
import kui.kernel.cluster.*
import kui.kernel.error.{ApplicationError, ErrorCode, InfrastructureError, KuiError}
import kui.kernel.{BrokerId, ClusterId, Host, KafkaClusterId, Port, Secret, TopicName, TopicPartition, PartitionId}

/** Hand-written stand-ins for the three use cases the routes are built on, plus the values they answer with.
  *
  * They are hand-written rather than generated by a mocking library (ADR-018) and they are *stubs*, not
  * fakes with behaviour: what these suites are testing is the routing, the mapping and the error handling,
  * so a use case that simply answers with what it was given is the right amount of collaborator. Anything
  * cleverer here would be a second implementation of the application layer, tested by nothing.
  */
object ClusterFixtures {

  val At: Instant = Instant.parse("2026-09-03T10:11:12Z")

  val Prod: ClusterId = ClusterId.unsafe("prod-eu")
  val Dead: ClusterId = ClusterId.unsafe("dead-cluster")

  /** The distinctive token every secret in a fixture profile is set to.
    *
    * A response body containing it is a leak, whichever field it came out of. This is R-12's contract-test
    * assertion, and it works only because the token appears nowhere a legitimate value could be.
    */
  val Canary: String = "kui-secret-canary"

  /** A profile whose every credential is the canary. Its *shape* — SASL_SSL, SCRAM-SHA-512, a truststore and
    * a keystore — is what a response may say; nothing else in it may reach the wire.
    */
  def profile(
      id: ClusterId = Prod,
      name: String = "Production EU",
      version: Long = 7L,
      readOnly: Boolean = false
  ): ClusterProfile =
    ClusterProfile
      .from(
        id = id,
        displayName = name,
        bootstrap = BootstrapServers.unsafe("broker-1.example.com:9093"),
        security = ClusterSecurity.Sasl(
          SaslProtocol.SaslSsl,
          SaslMechanism.ScramSha512(Canary, Secret(Canary)),
          Some(
            TlsConfig(
              truststore = Some(
                TrustStoreRef(StoreSource.Inline(Secret(Canary)), Some(Secret(Canary)), StoreType.Jks)
              ),
              keystore = Some(
                KeyStoreRef(
                  StoreSource.Inline(Secret(Canary)),
                  Some(Secret(Canary)),
                  Some(Secret(Canary)),
                  StoreType.Jks
                )
              ),
              verifyHostname = true,
              enabledProtocols = None,
              cipherSuites = None
            )
          )
        ),
        // `sasl.jaas.config` is reserved by the domain and refused outright, so the override that carries a
        // secret here is a truststore password: the key is publishable, the value is never.
        properties = ClientProperties.fromRaw(Map("ssl.truststore.password" -> Canary)),
        admin = AdminTuning.default,
        readOnly = readOnly,
        colour = None,
        version = ProfileVersion.unsafe(version),
        origin = ProfileOrigin.Static
      )
      .getOrElse(throw new IllegalStateException("the fixture profile is not valid"))

  def broker(id: Int, host: String = "broker-1.example.com", rack: Option[String] = Some("eu-west-1a")): Broker =
    Broker(
      BrokerId.unsafe(id),
      Host.unsafe(host),
      Port.unsafe(9093),
      rack.map(value => BrokerRack.from(value).getOrElse(throw new IllegalStateException("bad rack")))
    )

  def logDir(path: String = "/var/lib/kafka/data", error: Option[LogDirError] = None): LogDir =
    LogDir
      .from(
        LogDirPath.unsafe(path),
        error,
        Some(549755813888L),
        Some(366503875925L),
        List(
          ReplicaInfo(
            TopicPartition(TopicName.unsafe("orders"), PartitionId.unsafe(0)),
            1024L,
            0L,
            isFuture = false
          )
        )
      )
      .getOrElse(throw new IllegalStateException("the fixture log directory is not valid"))

  def topology(cluster: ClusterProfile = profile()): ClusterTopology = {
    val node = broker(1)

    ClusterTopology(
      cluster = cluster.ref,
      description = ClusterDescription
        .from(
          Some(KafkaClusterId.unsafe("MkU3OEVBNTcwNTJENDM2Qk")),
          Some(node),
          ControllerMode.KRaft,
          NonEmptyList.of(node),
          None
        )
        .getOrElse(throw new IllegalStateException("the fixture description is not valid")),
      version = KafkaVersion.parse("4.0.0", VersionSource.MetadataVersion).toOption,
      quorum = None,
      features = ClusterFeatures(Set(ClusterFeature.LogDirs), Set.empty, Set.empty, At),
      load = Map(
        node.id -> BrokerLoad(replicas = 3, leaders = None, skewPercent = Some(0.0d), logDirs = List(logDir()))
      ),
      partitions = None,
      topics = None
    )
  }

  // -----------------------------------------------------------------------------------------------
  // The stubs
  // -----------------------------------------------------------------------------------------------

  final class StubRegistry(
      profiles: List[ClusterProfile],
      published: Option[Stream[IO, RegistrySnapshot]] = None
  ) extends ClusterRegistry[IO] {

    private val byId: Map[ClusterId, ClusterProfile] = profiles.map(p => p.id -> p).toMap

    val snapshotValue: RegistrySnapshot =
      RegistrySnapshot(byId, RegistryVersion.Initial, StoreHealth.Online, At)

    def snapshot: IO[RegistrySnapshot] = IO.pure(snapshotValue)
    def list: IO[List[ClusterProfile]] = IO.pure(profiles)
    def refs: IO[List[ClusterRef]] = IO.pure(profiles.map(_.ref))
    def registryVersion: IO[RegistryVersion] = IO.pure(RegistryVersion.Initial)
    def reload: IO[RegistrySnapshot] = IO.pure(snapshotValue)
    def changes: Stream[IO, RegistrySnapshot] = published.getOrElse(Stream.emit(snapshotValue))

    def resolve(id: ClusterId): IO[Either[KuiError, ClusterProfile]] =
      IO.pure(
        byId
          .get(id)
          .toRight(
            ApplicationError.NotFound("cluster", id.value, ErrorCode.ClusterNotFound)
          )
      )
  }

  /** Answers with whatever view it was built with, and takes as long as it was told to over a refresh. */
  final class StubTopology(
      views: List[TopologyView],
      refreshTakes: FiniteDuration = Duration.Zero,
      refreshes: Option[Ref[IO, List[ClusterId]]] = None
  ) extends ClusterTopologyUseCase[IO] {

    private val byId: Map[ClusterId, TopologyView] = views.map(view => view.cluster.id -> view).toMap

    def viewAll: IO[List[TopologyView]] = IO.pure(views)

    def view(id: ClusterId): IO[Either[KuiError, TopologyView]] =
      IO.pure(byId.get(id).toRight(notFound(id)))

    def forceRefresh(id: ClusterId): IO[Either[KuiError, Unit]] =
      if !byId.contains(id) then IO.pure(Left(notFound(id)))
      else
        refreshes.traverse_(_.update(_ :+ id)) *>
          // The route must answer before this completes: a button whose latency is the cluster's latency
          // is exactly what the snapshot design removed from the page.
          IO.sleep(refreshTakes).start.as(Right(()))
  }

  final class StubBrokers(
      brokerList: Either[KuiError, BrokerList] = Left(notFound(Prod)),
      dirs: Either[KuiError, BrokerLogDirs] = Left(notFound(Prod)),
      configView: Either[KuiError, BrokerConfigView] = Left(notFound(Prod))
  ) extends BrokerDetailUseCase[IO] {

    def brokers(cluster: ClusterId): IO[Either[KuiError, BrokerList]] = IO.pure(brokerList)

    def logDirs(cluster: ClusterId, broker: BrokerId): IO[Either[KuiError, BrokerLogDirs]] = IO.pure(dirs)

    def partitionSizes(cluster: ClusterId, broker: BrokerId): IO[Either[KuiError, PartitionSizes]] =
      IO.pure(dirs.map(found => PartitionSizes.of(found.cluster, broker, found.dirs, found.freshness)))

    def logDirsAndSizes(
        cluster: ClusterId,
        broker: BrokerId
    ): IO[Either[KuiError, (BrokerLogDirs, PartitionSizes)]] =
      (logDirs(cluster, broker), partitionSizes(cluster, broker)).mapN((a, b) => (a, b).tupled)

    def configs(
        cluster: ClusterId,
        broker: BrokerId,
        includeDocs: Boolean
    ): IO[Either[KuiError, BrokerConfigView]] = IO.pure(configView)
  }

  /** A write use case that answers from a script and records what it was asked. */
  final class StubWrites(
      answer: ClusterProfile => Either[KuiError, ClusterProfile] = _.asRight[KuiError],
      takes: FiniteDuration = Duration.Zero,
      seen: Option[Ref[IO, List[(ClusterProfile, ProfileVersion)]]] = None,
      deleted: ClusterId => Either[KuiError, Unit] = _ => Right(())
  ) extends ClusterWriteUseCase[IO] {

    def put(profile: ClusterProfile, expected: ProfileVersion): IO[Either[KuiError, ClusterProfile]] =
      seen.traverse_(_.update(_ :+ ((profile, expected)))) *>
        // The store's contract is that a write is readable back before it returns, so the wait belongs
        // inside this call: a route that answered first would be answering before the fact.
        IO.sleep(takes).as(answer(profile))

    def delete(id: ClusterId, expected: ProfileVersion): IO[Either[KuiError, Unit]] =
      IO.sleep(takes).as(deleted(id))
  }

  /** A probe that always says the same thing. The verdict is a parameter because the three verdicts are the
    * whole point of the endpoint.
    */
  final class StubProbe(verdict: Connectivity = Connectivity.Reachable)
      extends kui.cluster.application.ClusterProbeUseCase[IO] {

    def probe(profile: ClusterProfile): IO[Either[KuiError, Connectivity]] =
      IO.pure(Right(verdict))
  }

  def notFound(id: ClusterId): KuiError =
    ApplicationError.NotFound("cluster", id.value, ErrorCode.ClusterNotFound)

  def unreachable(name: String = "prod-eu"): KuiError =
    InfrastructureError.Unreachable(name, "connection refused")
}
