#!/usr/bin/env bash
# Generates the certificate material `docker-compose.secured.yml` mounts, using nothing but Docker.
#
# Three files land in ./certs:
#
#   broker.keystore.p12   the broker's private key and its certificate, signed by the CA below.
#                         Its subject alternative names include `kafka-secured`, which is the
#                         Compose service name KUI connects to -- with hostname verification left
#                         ON, as any real deployment should, a certificate that does not name the
#                         address is a certificate the handshake rejects.
#   kafka-ca.p12          the CA certificate alone. This is the truststore KUI is given, and the
#                         only one of the three a KUI operator would ever hold.
#   ca.pem                the same certificate in PEM, for anyone wanting to inspect it.
#
# Nothing here is a secret worth keeping: it is a throwaway authority for a demonstration broker,
# regenerated by re-running this script. ./certs is git-ignored all the same, because a private key
# in a repository teaches the wrong habit even when the key is worthless.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
password="kui-secured-demo"

rm -rf "$here/certs"
mkdir -p "$here/certs"

docker run --rm -v "$here/certs:/certs" -w /certs eclipse-temurin:21-jdk bash -c "
set -e
P='$password'

# The authority.
keytool -genkeypair -alias ca -keyalg RSA -keysize 2048 -validity 3650 \
  -dname 'CN=KUI Secured Demo CA,O=KUI' -ext bc:c \
  -keystore ca.p12 -storetype PKCS12 -storepass \$P -keypass \$P >/dev/null
keytool -exportcert -alias ca -keystore ca.p12 -storepass \$P -rfc -file ca.pem >/dev/null

# The broker's key, signed by it. The SAN list is what makes hostname verification pass.
keytool -genkeypair -alias broker -keyalg RSA -keysize 2048 -validity 3650 \
  -dname 'CN=kafka-secured,O=KUI' -ext 'san=dns:kafka-secured,dns:localhost,ip:127.0.0.1' \
  -keystore broker.keystore.p12 -storetype PKCS12 -storepass \$P -keypass \$P >/dev/null
keytool -certreq -alias broker -keystore broker.keystore.p12 -storepass \$P -file broker.csr >/dev/null
keytool -gencert -alias ca -keystore ca.p12 -storepass \$P -infile broker.csr \
  -ext 'san=dns:kafka-secured,dns:localhost,ip:127.0.0.1' -validity 3650 -rfc -outfile broker.pem >/dev/null
keytool -importcert -alias ca -keystore broker.keystore.p12 -storepass \$P -file ca.pem -noprompt >/dev/null
keytool -importcert -alias broker -keystore broker.keystore.p12 -storepass \$P -file broker.pem -noprompt >/dev/null

# The truststore KUI gets: the CA and nothing else.
keytool -importcert -alias ca -keystore kafka-ca.p12 -storetype PKCS12 -storepass \$P \
  -file ca.pem -noprompt >/dev/null

rm -f broker.csr ca.p12 broker.pem
chmod 644 kafka-ca.p12 broker.keystore.p12 ca.pem
"

echo "wrote $here/certs: $(ls "$here/certs" | tr '\n' ' ')"
