package kui.tools

import java.nio.file.Paths

import munit.FunSuite

import kui.kernel.error.ErrorCode

/** The generator's one refusal, and the fact that it is not refusing today.
  *
  * `BrowserConstants.render` answers `Left` for exactly one thing, and it is not staleness: an RBAC
  * vocabulary in which a connector action's fallback is spelled differently from the action itself. The
  * browser's permission evaluator reads `ConnectorFallbackActions` as a *list* and applies the same action
  * name to the parent connect cluster, so a differently-named parent would silently grant or withhold the
  * wrong permission -- a disabled button, which looks exactly like a permission the user does not hold.
  *
  * Until 2026-09-07 that refusal was a `throw` inside a private method whose only caller was the renderer,
  * over a fold of `Action.values` that no test can put into the failing state. It failed `DisableSyntax` and
  * nothing could reach it. It is now a value over the pairs, which is what makes the two cases below possible
  * at all.
  */
final class BrowserConstantsSuite extends FunSuite {

  test("a fallback spelled differently from its own action is named, in both directions") {
    val mismatched = BrowserConstants.mismatchedFallbacks(
      List("EDIT" -> "EDIT", "RESTART" -> "OPERATE", "VIEW" -> "VIEW", "DELETE" -> "REMOVE")
    )

    assertEquals(mismatched, List("RESTART -> OPERATE", "DELETE -> REMOVE"))
    assert(clue(BrowserConstants.fallbackProblem(mismatched)).contains("RESTART -> OPERATE"))
  }

  test("the vocabulary this build ships has no mismatch, so the file renders") {
    val declared = BrowserConstants.declaredFallbacks

    assert(declared.nonEmpty, "no connector action declares a parent fallback at all")
    assertEquals(BrowserConstants.mismatchedFallbacks(declared), Nil)
    assert(BrowserConstants.render(ErrorCode.values.toList).isRight)
  }

  test("a mismatch refuses the whole rendering rather than emitting a list the browser misreads") {
    // The seam, not the fold: `render` is what `BrowserConstantsMain` calls, and what it must not do is
    // return a `Right` carrying a `ConnectorFallbackActions` array whose names do not mean what the
    // evaluator assumes. Feeding the check the vocabulary's own pairs with one renamed shows the sentence
    // the caller would print; feeding it the real ones shows the file rendering.
    val renamed = BrowserConstants.declaredFallbacks.map((action, parent) => (action, parent + "_RENAMED"))

    val problem = BrowserConstants.fallbackProblem(BrowserConstants.mismatchedFallbacks(renamed))
    assert(problem.contains("_RENAMED"), problem)
    assert(problem.contains("fix both together"), problem)

    BrowserConstants.render(ErrorCode.values.toList) match {
      case Right(rendered) => assert(rendered.contains("export const ConnectorFallbackActions"), rendered)
      case Left(unexpected) => fail(s"the shipped vocabulary should render: $unexpected")
    }
  }

  test("render itself refuses a renamed fallback, and not only the function that spots one") {
    /*
     * The seam the three cases above did not have. They exercise `mismatchedFallbacks` and
     * `fallbackProblem`, which are pure functions over pairs, and never the decision inside `render` that
     * reads them -- so `vocabulary`'s check could be deleted whole, leaving `Right(rbacLines)`, with
     * `./mill tools.errorCodes.test` at 291/291 and `frontend.apiConstants --check` green, because the
     * generated bytes are identical either way. The pairs are a parameter of `render` now, so this case
     * puts the real renderer in the state it exists to refuse.
     */
    val renamed = BrowserConstants.declaredFallbacks.map((action, parent) => (action, parent + "_RENAMED"))
    assert(renamed.nonEmpty, "no connector action declares a parent fallback at all")

    BrowserConstants.render(ErrorCode.values.toList, renamed) match {
      case Left(problem) =>
        assert(problem.contains("_RENAMED"), problem)
        assert(problem.contains("fix both together"), problem)
      case Right(rendered) =>
        fail(s"a renamed fallback must refuse the whole file, not emit it: ${rendered.take(200)}")
    }

    // And the other direction, so the case cannot pass by refusing everything.
    assert(BrowserConstants.render(ErrorCode.values.toList, BrowserConstants.declaredFallbacks).isRight)
  }

  test("the one-argument render reads the vocabulary the enum declares, and emits the list it checked") {
    /*
     * Two holes in one case, and they are the same hole twice.
     *
     * `render(codes)` delegates, and until the emitted array came off the checked pairs it could have
     * delegated to `Nil` with every case green and the generated bytes unmoved: the check ran over one
     * derivation of the fallbacks and `rbacLines` emitted a second, so emptying the first changed nothing
     * anybody could see. Checking one list while emitting another is the defect the check exists to
     * prevent, one level in. The emitted array is the checked list now, so the two assertions below pin
     * both: what `render(codes)` passes down, and that what came out is what went in.
     */
    val declared = BrowserConstants.declaredFallbacks
    assert(declared.nonEmpty, "no connector action declares a parent fallback at all")

    val shipped = BrowserConstants.render(ErrorCode.values.toList).toOption.get
    assertEquals(shipped, BrowserConstants.render(ErrorCode.values.toList, declared).toOption.get)

    val emitted = shipped.linesIterator
      .dropWhile(!_.startsWith("export const ConnectorFallbackActions"))
      .drop(1)
      .takeWhile(_ != "];")
      .map(_.trim.stripSuffix(",").stripPrefix("\"").stripSuffix("\""))
      .toList
    assertEquals(emitted, declared.map((action, _) => action))

    // Handed no pairs, the file renders an empty array rather than the vocabulary's own: the emission
    // follows the check, so a check over nothing publishes nothing.
    val empty = BrowserConstants.render(ErrorCode.values.toList, Nil).toOption.get
    assert(empty.contains("export const ConnectorFallbackActions: readonly string[] = [\n];"), empty)
  }

  test("a refused rendering writes no file and exits non-zero, in both modes") {
    /*
     * `BrowserConstantsMain`'s refusal was `println` then `sys.exit(1)` inside `main`, which no case can
     * call: replacing it with `case Left(_) => ()` left every gate green and would have had the generator
     * write nothing, say nothing and exit zero on the one input it exists to refuse. `decide` is the same
     * decision as a value.
     */
    val target = Paths.get("frontend", "packages", "api", "src", "constants.generated.ts")
    for checkOnly <- List(false, true) do {
      val outcome = BrowserConstantsMain.decide(target, checkOnly, Left("a fallback was renamed"), None)
      assertEquals(outcome.status, 1, clue = s"checkOnly=$checkOnly")
      assertEquals(outcome.write, None, clue = "a file that would be wrong must not be written")
      assert(outcome.message.contains("a fallback was renamed"), outcome.message)
    }
  }

  test("--check fails on a missing file and on a stale one, and passes on the file it would write") {
    val target = Paths.get("frontend", "packages", "api", "src", "constants.generated.ts")
    val rendered = Right("export const CsrfHeaderName = \"X-Csrf-Token\" as const;\n")

    val missing = BrowserConstantsMain.decide(target, checkOnly = true, rendered, None)
    assertEquals(missing.status, 1)
    assert(missing.message.contains("does not exist"), missing.message)

    val stale = BrowserConstantsMain.decide(target, checkOnly = true, rendered, Some("something else"))
    assertEquals(stale.status, 1)
    assert(stale.message.contains("out of date"), stale.message)

    val fresh = BrowserConstantsMain.decide(target, checkOnly = true, rendered, rendered.toOption)
    assertEquals(fresh.status, 0)
    assertEquals(fresh.write, None, clue = "--check must never write")
    assert(fresh.message.contains("up to date"), fresh.message)
  }

  test("without --check the rendering is what gets written, byte for byte") {
    val target = Paths.get("frontend", "packages", "api", "src", "constants.generated.ts")
    val expected = BrowserConstants.render(ErrorCode.values.toList).toOption.get

    // The committed content is deliberately different: a write mode that consulted it would be a check.
    val outcome = BrowserConstantsMain.decide(target, checkOnly = false, Right(expected), Some("stale"))

    assertEquals(outcome.status, 0)
    assertEquals(outcome.write, Some(expected))
    assert(outcome.message.startsWith("wrote "), outcome.message)
  }

  test("a stale --check ends the process non-zero, and a fresh one does not end it at all") {
    /*
     * The seam the case above does not have. `decide` was already a value, and the mutation that mattered was
     * one operator past it: `if outcome.status != 0 then sys.exit(...)` was the last line of `main`, so
     * changing `!= 0` to `< 0` left `./mill tools.errorCodes.test` and `./mill frontend.apiConstants --check`
     * both green while a genuinely stale `constants.generated.ts` printed "is out of date" and exited zero.
     * The CI step that exists to catch a forgotten regeneration would have passed it. `exitStatus` is that
     * operator as a value, driven here from the two outcomes `decide` actually produces rather than from a
     * hand-built `Outcome`, so the case fails if either half of the translation is reversed.
     */
    val target = Paths.get("frontend", "packages", "api", "src", "constants.generated.ts")
    val rendered = Right("export const CsrfHeaderName = \"X-Csrf-Token\" as const;\n")

    val stale = BrowserConstantsMain.decide(target, checkOnly = true, rendered, Some("something else"))
    assertEquals(BrowserConstantsMain.exitStatus(stale), Some(1))

    val fresh = BrowserConstantsMain.decide(target, checkOnly = true, rendered, rendered.toOption)
    assertEquals(BrowserConstantsMain.exitStatus(fresh), None)

    // The refusal too: a vocabulary that cannot be rendered must not exit zero either.
    val refused = BrowserConstantsMain.decide(target, checkOnly = false, Left("a renamed fallback"), None)
    assertEquals(BrowserConstantsMain.exitStatus(refused), Some(1))
  }
}
