package kui.tools

import java.nio.file.Paths

import munit.FunSuite

import kui.kernel.error.ErrorCode

/** That the rendering is exact, sorted and complete. */
final class ErrorCodeDocSuite extends FunSuite {

  test("two codes render to the exact expected Markdown") {
    val rendered = ErrorCodeDoc.render(List(ErrorCode.Timeout, ErrorCode.ClusterNotFound))

    assertNoDiff(
      rendered,
      s"""${ErrorCodeDoc.GeneratedWarning}
         |
         |# Error codes
         |
         |Every KUI failure carries one of these codes in the `code` field of the error envelope
         |(ADR-034). The code is stable: it is what a log query and a browser switch on, so renaming
         |one is a breaking change. `Retryable` means the same request, unchanged, could succeed later.
         |
         || Code | HTTP | Retryable | Area | Meaning |
         || --- | --- | --- | --- | --- |
         || `KUI-CLUSTER-NOT-FOUND` | 404 | no | CLUSTER | No cluster with this id is configured in KUI. |
         || `KUI-TIMEOUT` | 408 | yes | TIMEOUT | The operation did not finish inside its time budget. |
         |""".stripMargin
    )
  }

  test("the table is sorted by code, so a new case makes a one-line diff") {
    val rendered = ErrorCodeDoc.render(ErrorCode.values.toList)
    val codes    = rendered.linesIterator.filter(_.startsWith("| `")).map(_.split('`')(1)).toList

    assertEquals(codes, codes.sorted)
  }

  test("every code appears exactly once") {
    val rendered = ErrorCodeDoc.render(ErrorCode.values.toList)

    ErrorCode.values.foreach { code =>
      val occurrences = rendered.linesIterator.count(_.contains(s"`${code.wire}`"))
      assertEquals(occurrences, 1, clue = code.wire)
    }
  }

  test("the document says it is generated and how to regenerate it") {
    val rendered = ErrorCodeDoc.render(ErrorCode.values.toList)

    assert(rendered.startsWith("<!-- Generated by `./mill docs.errorCodes`"), rendered.take(80))
    assert(rendered.contains("Do not edit by hand"))
  }

  test("the rendering does not depend on the order the cases are given in") {
    assertEquals(
      ErrorCodeDoc.render(ErrorCode.values.toList),
      ErrorCodeDoc.render(ErrorCode.values.toList.reverse)
    )
  }

  test("--check fails on a missing document and on a stale one, and passes on the one it would write") {
    val target = Paths.get("docs", "api", "error-codes.md")
    val expected = ErrorCodeDoc.render(ErrorCode.values.toList)

    val missing = ErrorCodeDocMain.decide(target, checkOnly = true, expected, None)
    assertEquals(missing.status, 1)
    assert(missing.message.contains("does not exist"), missing.message)

    val stale = ErrorCodeDocMain.decide(target, checkOnly = true, expected, Some("something else"))
    assertEquals(stale.status, 1)
    assert(stale.message.contains("out of date"), stale.message)

    val fresh = ErrorCodeDocMain.decide(target, checkOnly = true, expected, Some(expected))
    assertEquals(fresh.status, 0)
    assertEquals(fresh.write, None, clue = "--check must never write")
    assert(fresh.message.contains("up to date"), fresh.message)
  }

  test("without --check the rendering is what gets written, byte for byte") {
    val target = Paths.get("docs", "api", "error-codes.md")
    val expected = ErrorCodeDoc.render(ErrorCode.values.toList)

    // The committed content is deliberately different: a write mode that consulted it would be a check.
    val outcome = ErrorCodeDocMain.decide(target, checkOnly = false, expected, Some("stale"))

    assertEquals(outcome.status, 0)
    assertEquals(outcome.write, Some(expected))
    assert(outcome.message.startsWith("wrote "), outcome.message)
  }

  test("a stale --check ends the process non-zero, and a fresh one does not end it at all") {
    /*
     * Everything above this case was inside `main` until 2026-09-10, so none of it could be driven: this
     * object had no suite over its two modes at all, and the operator that turns a decision into an exit
     * status is where its sibling's measured hole was (`!= 0` -> `< 0`, after which a stale file printed
     * "is out of date" and exited zero). Both halves are asserted, because a translation that always exits
     * and one that never does are equally wrong and only one of them is loud.
     */
    val target = Paths.get("docs", "api", "error-codes.md")
    val expected = ErrorCodeDoc.render(ErrorCode.values.toList)

    val stale = ErrorCodeDocMain.decide(target, checkOnly = true, expected, Some("something else"))
    assertEquals(ErrorCodeDocMain.exitStatus(stale), Some(1))

    val fresh = ErrorCodeDocMain.decide(target, checkOnly = true, expected, Some(expected))
    assertEquals(ErrorCodeDocMain.exitStatus(fresh), None)
  }
}
