package kui.tools

import munit.FunSuite

import kui.kernel.error.ErrorCode

/** That the rendering is exact, sorted and complete. */
final class ErrorCodeDocSuite extends FunSuite {

  test("two codes render to the exact expected Markdown") {
    val rendered = ErrorCodeDoc.render(List(ErrorCode.Timeout, ErrorCode.ClusterNotFound))

    assertNoDiff(
      rendered,
      s"""${ErrorCodeDoc.GeneratedWarning}
         |
         |# Error codes
         |
         |Every KUI failure carries one of these codes in the `code` field of the error envelope
         |(ADR-034). The code is stable: it is what a log query and a browser switch on, so renaming
         |one is a breaking change. `Retryable` means the same request, unchanged, could succeed later.
         |
         || Code | HTTP | Retryable | Area | Meaning |
         || --- | --- | --- | --- | --- |
         || `KUI-CLUSTER-NOT-FOUND` | 404 | no | CLUSTER | No cluster with this id is configured in KUI. |
         || `KUI-TIMEOUT` | 408 | yes | TIMEOUT | The operation did not finish inside its time budget. |
         |""".stripMargin
    )
  }

  test("the table is sorted by code, so a new case makes a one-line diff") {
    val rendered = ErrorCodeDoc.render(ErrorCode.values.toList)
    val codes    = rendered.linesIterator.filter(_.startsWith("| `")).map(_.split('`')(1)).toList

    assertEquals(codes, codes.sorted)
  }

  test("every code appears exactly once") {
    val rendered = ErrorCodeDoc.render(ErrorCode.values.toList)

    ErrorCode.values.foreach { code =>
      val occurrences = rendered.linesIterator.count(_.contains(s"`${code.wire}`"))
      assertEquals(occurrences, 1, clue = code.wire)
    }
  }

  test("the document says it is generated and how to regenerate it") {
    val rendered = ErrorCodeDoc.render(ErrorCode.values.toList)

    assert(rendered.startsWith("<!-- Generated by `./mill docs.errorCodes`"), rendered.take(80))
    assert(rendered.contains("Do not edit by hand"))
  }

  test("the rendering does not depend on the order the cases are given in") {
    assertEquals(
      ErrorCodeDoc.render(ErrorCode.values.toList),
      ErrorCodeDoc.render(ErrorCode.values.toList.reverse)
    )
  }
}
