package kui.ui.shell

/** The shell's class names, as Scala constants.
  *
  * The same arrangement `KernelCss` uses and for the same reason: a class name typed as a string literal at
  * the point of use is a name that can be misspelled, renamed in the stylesheet only, or deleted from the
  * stylesheet while the code still writes it. Here the compiler catches all three.
  */
object ShellCss {

  val Shell = "kui-shell"
  val SkipLink = "kui-shell__skip"
  val Header = "kui-shell__header"
  val Brand = "kui-shell__brand"
  val BrandMark = "kui-shell__brand-mark"
  val BrandName = "kui-shell__brand-name"
  val HeaderSpacer = "kui-shell__header-spacer"
  val HeaderActions = "kui-shell__header-actions"
  val HeaderVersion = "kui-shell__version"

  /** The account control in the header, and the menu it opens. */
  val UserMenu = "kui-shell__user"
  val UserMenuAnchor = "kui-shell__user-anchor"
  val UserMenuName = "kui-shell__user-name"
  val UserMenuPanel = "kui-shell__user-panel"
  val UserMenuIdentity = "kui-shell__user-identity"
  val UserMenuIdentityName = "kui-shell__user-identity-name"
  val UserMenuRoles = "kui-shell__user-roles"
  val UserMenuItem = "kui-shell__user-item"
  val Sidebar = "kui-shell__sidebar"
  val SidebarList = "kui-shell__sidebar-list"
  val SidebarLink = "kui-shell__sidebar-link"
  val SidebarLinkCurrent = "kui-shell__sidebar-link--current"
  val SidebarLinkDimmed = "kui-shell__sidebar-link--dimmed"
  val SidebarLinkDisabled = "kui-shell__sidebar-link--disabled"
  val SidebarLinkLabel = "kui-shell__sidebar-link-label"
  val SidebarLinkDot = "kui-shell__sidebar-link-dot"

  val ClusterSwitcher = "kui-shell__cluster-switcher"
  val ClusterSwitcherTrigger = "kui-shell__cluster-switcher-trigger"
  val ClusterSwitcherCaret = "kui-shell__cluster-switcher-caret"
  val ClusterSwitcherCaretOpen = "kui-shell__cluster-switcher-caret--open"
  val ClusterSwitcherList = "kui-shell__cluster-switcher-list"
  val ClusterSwitcherOption = "kui-shell__cluster-switcher-option"
  val ClusterSwitcherOptionCurrent = "kui-shell__cluster-switcher-option--current"
  val ClusterSwitcherRow = "kui-shell__cluster-switcher-row"
  val ClusterSwitcherName = "kui-shell__cluster-switcher-name"
  val ClusterSwitcherEmpty = "kui-shell__cluster-switcher-empty"
  val ClusterSwitcherColour = "kui-shell__cluster-switcher-colour"

  /** The status dot. A circle, where the colour tag beside it is a rounded rectangle. */
  val ClusterSwitcherDot = "kui-shell__cluster-dot"
  val ClusterDotReady = "kui-shell__cluster-dot--ready"
  val ClusterDotDegraded = "kui-shell__cluster-dot--degraded"
  val ClusterDotUnavailable = "kui-shell__cluster-dot--unavailable"
  val ClusterDotNeutral = "kui-shell__cluster-dot--neutral"
  val DashboardHeader = "kui-shell__dashboard-header"
  val DashboardLead = "kui-shell__dashboard-lead"
  val DashboardStrip = "kui-shell__dashboard-strip"
  val DashboardTile = "kui-shell__dashboard-tile"
  val DashboardTileValue = "kui-shell__dashboard-tile-value"
  val DashboardTileLabel = "kui-shell__dashboard-tile-label"
  val DashboardTileNote = "kui-shell__dashboard-tile-note"
  val DashboardFetched = "kui-shell__dashboard-fetched"
  val DashboardCards = "kui-shell__dashboard-cards"
  val DashboardCard = "kui-shell__dashboard-card"
  val DashboardCardHead = "kui-shell__dashboard-card-head"
  val DashboardCardName = "kui-shell__dashboard-card-name"
  val DashboardPanels = "kui-shell__dashboard-panels"
  val DashboardPanel = "kui-shell__dashboard-panel"
  val DashboardPanelHead = "kui-shell__dashboard-panel-head"
  val DashboardPanelTitle = "kui-shell__dashboard-panel-title"
  val DashboardPanelLink = "kui-shell__dashboard-panel-link"
  val DashboardPanelStale = "kui-shell__dashboard-panel--stale"
  val DashboardPanelReason = "kui-shell__dashboard-panel-reason"
  val DashboardPanelNote = "kui-shell__dashboard-panel-note"
  val DashboardFigure = "kui-shell__dashboard-figure"
  val DashboardFigureLabel = "kui-shell__dashboard-figure-label"
  val DashboardFigureValue = "kui-shell__dashboard-figure-value"
  val DashboardBars = "kui-shell__dashboard-bars"
  val DashboardBarsTitle = "kui-shell__dashboard-bars-title"
  val DashboardError = "kui-shell__dashboard-error"

  val Content = "kui-shell__content"
  val Page = "kui-shell__page"
  val PageError = "kui-shell__page-error"
  val PageErrorDetail = "kui-shell__page-error-detail"
  val Gallery = "kui-shell__gallery"
  val GallerySection = "kui-shell__gallery-section"
  val GalleryRow = "kui-shell__gallery-row"
  val GallerySwatch = "kui-shell__gallery-swatch"
  val GalleryIconGrid = "kui-shell__gallery-icons"
  val GalleryIcon = "kui-shell__gallery-icon"
  val SettingsGroup = "kui-shell__settings-group"

  val ErrorPage = "kui-shell__error-page"
  val ErrorPageDetail = "kui-shell__error-page-detail"

  val CapabilityBanner = "kui-shell__capability-banner"
  val CapabilityBannerBody = "kui-shell__capability-banner-body"
  val CapabilityBannerIcon = "kui-shell__capability-banner-icon"
  val CapabilityBannerText = "kui-shell__capability-banner-text"

  val Fallback = "kui-shell__fallback"
  val FallbackTitle = "kui-shell__fallback-title"
  val FallbackReason = "kui-shell__fallback-reason"
  val FallbackReasonIcon = "kui-shell__fallback-reason-icon"
  val FallbackSince = "kui-shell__fallback-since"
  val FallbackFeatureContent = "kui-shell__fallback-feature"
  val FallbackActions = "kui-shell__fallback-actions"
  val FallbackError = "kui-shell__fallback-error"
  val FallbackStillWorks = "kui-shell__fallback-still-works"
  val FallbackStillWorksTitle = "kui-shell__fallback-still-works-title"
  val FallbackStillWorksEmpty = "kui-shell__fallback-still-works-empty"

  val FeatureLoading = "kui-shell__feature-loading"
  val FeatureLoadingIcon = "kui-shell__feature-loading-icon"
  val FeatureLoadingLabel = "kui-shell__feature-loading-label"

  /** The sign-in screen (see `page/LoginPage.scala`). It shares the unreachable screen's full-page shape
    * because it is the same kind of thing: one card, nothing behind it usable, no data fetched to draw it.
    */
  val Login = "kui-shell__login"
  val LoginCard = "kui-shell__login-card"
  val LoginTitle = "kui-shell__login-title"
  val LoginFields = "kui-shell__login-fields"
  val LoginField = "kui-shell__login-field"
  val LoginLabel = "kui-shell__login-label"
  val LoginInput = "kui-shell__login-input"
  val LoginError = "kui-shell__login-error"
  val LoginNotice = "kui-shell__login-notice"
  val LoginHint = "kui-shell__login-hint"

  val Unreachable = "kui-shell__unreachable"
  val UnreachableCard = "kui-shell__unreachable-card"
  val UnreachableIcon = "kui-shell__unreachable-icon"
  val UnreachableCountdown = "kui-shell__unreachable-countdown"
  val UnreachableLastContact = "kui-shell__unreachable-last-contact"
}
