// Generated by `./mill frontend.apiConstants` from `kui.contracts.HttpHeaders` and the
// `kui.kernel.error.ErrorCode` and `kui.contracts.capability.ReasonCode` enums, the
// `kui.contracts.sse.SseEventName` constants and the `kui.security.rbac` vocabulary. Do not
// edit by hand: your change will be overwritten.

/**
 * The strings the browser and the server must spell identically.
 *
 * `ErrorCodes` is the vocabulary of the error envelope's `code` field (ADR-034). Branch on these
 * constants and never on a message: a message is display text and may be reworded in any release,
 * while a code is a contract and renaming one is a breaking change.
 *
 * A code KUI does not know is still a valid code — a browser built against an older server must
 * render a response from a newer one — so `ErrorCode` is a union of the known names *plus* string,
 * and code that switches on it always needs a default branch.
 */
export const CsrfHeaderName = "X-Csrf-Token" as const;

export const ErrorCodes = {
  /** HTTP 404. No cluster with this id is configured in KUI. */
  ClusterNotFound: "KUI-CLUSTER-NOT-FOUND",
  /** HTTP 409. The configuration changed since it was read; re-read it and apply the change again. */
  ConfigVersionConflict: "KUI-CONFIG-VERSION-CONFLICT",
  /** HTTP 409, retryable. The Kafka Connect cluster is rebalancing and cannot answer yet; retry shortly. */
  ConnectRebalancing: "KUI-CONNECT-REBALANCING",
  /** HTTP 400. The connector offsets in the request are not valid for this connector. */
  ConnectorOffsets: "KUI-CONNECTOR-OFFSETS",
  /** HTTP 400. The paging cursor is past its expiry; start the listing again. */
  CursorExpired: "KUI-CURSOR-EXPIRED",
  /** HTTP 400. The paging cursor is malformed, was not signed by this deployment, or is for another topic. */
  CursorInvalid: "KUI-CURSOR-INVALID",
  /** HTTP 400. The paging cursor exceeds the size limit; narrow the request to fewer partitions. */
  CursorTooLarge: "KUI-CURSOR-TOO-LARGE",
  /** HTTP 400. The smart filter expression could not be compiled. */
  FilterCompile: "KUI-FILTER-COMPILE",
  /** HTTP 403. The authenticated principal does not hold a role that permits this operation. */
  Forbidden: "KUI-FORBIDDEN",
  /** HTTP 409. The consumer group still has members, so its offsets cannot be changed or deleted. */
  GroupNotEmpty: "KUI-GROUP-NOT-EMPTY",
  /** HTTP 404. No consumer group with this id exists on this cluster. */
  GroupNotFound: "KUI-GROUP-NOT-FOUND",
  /** HTTP 500. KUI failed unexpectedly; the correlation id ties this response to the server-side log. */
  Internal: "KUI-INTERNAL",
  /** HTTP 409. The target is not in a state where this operation is allowed. */
  InvalidState: "KUI-INVALID-STATE",
  /** HTTP 405. The cluster is configured read-only, so no operation that changes it is accepted. */
  ReadOnly: "KUI-READ-ONLY",
  /** HTTP 404. No endpoint matches this method and path. */
  RouteNotFound: "KUI-ROUTE-NOT-FOUND",
  /** HTTP 404. The subject or schema version does not exist in the schema registry. */
  SchemaNotFound: "KUI-SCHEMA-NOT-FOUND",
  /** HTTP 503, retryable. The requested serde exists but cannot work right now, usually because its schema registry is unreachable. */
  SerdeUnavailable: "KUI-SERDE-UNAVAILABLE",
  /** HTTP 500. An encrypted field in the metadata store could not be decrypted with any configured key. */
  StoreCrypto: "KUI-STORE-CRYPTO",
  /** HTTP 500. A record in the metadata store is not a readable envelope for this version of KUI. */
  StoreEnvelope: "KUI-STORE-ENVELOPE",
  /** HTTP 501. No metadata store is configured, so this change cannot be persisted; configure kui.store.kafka.* to enable it. */
  StoreNotConfigured: "KUI-STORE-NOT-CONFIGURED",
  /** HTTP 503, retryable. The metadata store's log could not be replayed to its end within the configured timeout. */
  StoreReplayTimeout: "KUI-STORE-REPLAY-TIMEOUT",
  /** HTTP 500. An existing metadata-store topic has settings KUI cannot use, and KUI never rewrites an existing topic's configuration. */
  StoreTopicIncompatible: "KUI-STORE-TOPIC-INCOMPATIBLE",
  /** HTTP 503, retryable. KUI's metadata store could not be reached; reads are served from the last replayed state and writes are rejected. */
  StoreUnavailable: "KUI-STORE-UNAVAILABLE",
  /** HTTP 408, retryable. The operation did not finish inside its time budget. */
  Timeout: "KUI-TIMEOUT",
  /** HTTP 404. The topic does not exist on this cluster. */
  TopicNotFound: "KUI-TOPIC-NOT-FOUND",
  /** HTTP 401. The request carried no valid identity; sign in, or check the signed principal header. */
  Unauthenticated: "KUI-UNAUTHENTICATED",
  /** HTTP 501. This cluster or upstream does not support the requested feature. */
  Unsupported: "KUI-UNSUPPORTED",
  /** HTTP 502. KUI's credentials for the upstream system were rejected; the configuration needs fixing. */
  UpstreamAuth: "KUI-UPSTREAM-AUTH",
  /** HTTP 502, retryable. ksqlDB answered with an error or an unusable response. */
  UpstreamKsql: "KUI-UPSTREAM-KSQL",
  /** HTTP 503, retryable. The upstream system could not be reached, or its circuit breaker is open. */
  UpstreamUnavailable: "KUI-UPSTREAM-UNAVAILABLE",
  /** HTTP 400. The request is not valid; the details array names each field and what it must satisfy. */
  Validation: "KUI-VALIDATION",
} as const;

/** One of the codes this build knows about. */
export type KnownErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/**
 * Any code an envelope can carry. The `(string & {})` arm keeps a code from a newer server
 * decodable while still offering the known names to autocompletion.
 */
// eslint-disable-next-line @typescript-eslint/ban-types
export type ErrorCode = KnownErrorCode | (string & {});

/** Every known code, for tests and for exhaustiveness checks over the vocabulary. */
export const AllErrorCodes: readonly KnownErrorCode[] = Object.values(ErrorCodes);

/**
 * The four values of a capability's `status` field (ADR-032).
 *
 * This field is the discriminator the wire carries and the OpenAPI document does not describe, so it
 * is the one part of a capability frame a hand-written decoder has to read. See
 * `kui.contracts.capability.CapabilityState`, whose Circe codec writes it.
 */
export const CapabilityStatuses = {
  Available: "available",
  Degraded: "degraded",
  Unavailable: "unavailable",
  NotConfigured: "not_configured",
} as const;

export type CapabilityStatus = (typeof CapabilityStatuses)[keyof typeof CapabilityStatuses];

/**
 * Why a capability is not fully available.
 *
 * As with `ErrorCode`, a reason a newer gateway invents must not stop an older browser reading the
 * frame: anything unrecognised decodes to `Unknown` rather than failing.
 */
export const ReasonCodes = {
  /** The cluster is not answering. */
  UpstreamUnavailable: "UPSTREAM_UNAVAILABLE",
  /** The cluster is answering too slowly. */
  UpstreamTimeout: "UPSTREAM_TIMEOUT",
  /** KUI has paused its calls while the cluster recovers. */
  CircuitOpen: "CIRCUIT_OPEN",
  /** KUI's credentials for this cluster were rejected. */
  UpstreamAuth: "UPSTREAM_AUTH",
  /** This deployment has no such thing configured. */
  NotConfigured: "NOT_CONFIGURED",
  /** You are not allowed to see this. */
  Forbidden: "FORBIDDEN",
  /** KUI has not finished reading this cluster yet. */
  Starting: "STARTING",
  /** KUI could not refresh this. */
  Unknown: "UNKNOWN",
} as const;

export type KnownReasonCode = (typeof ReasonCodes)[keyof typeof ReasonCodes];

/**
 * The sentence to show a person for each reason, as reviewed on the server.
 *
 * Written about KUI's relationship with the cluster rather than about HTTP: "the cluster is not
 * answering" is something an operator can go and check, where "kafka answered with status 502" names
 * a status no broker can return.
 */
export const ReasonSentences: Readonly<Record<KnownReasonCode, string>> = {
  [ReasonCodes.UpstreamUnavailable]: "the cluster is not answering",
  [ReasonCodes.UpstreamTimeout]: "the cluster is answering too slowly",
  [ReasonCodes.CircuitOpen]: "KUI has paused its calls while the cluster recovers",
  [ReasonCodes.UpstreamAuth]: "KUI's credentials for this cluster were rejected",
  [ReasonCodes.NotConfigured]: "this deployment has no such thing configured",
  [ReasonCodes.Forbidden]: "you are not allowed to see this",
  [ReasonCodes.Starting]: "KUI has not finished reading this cluster yet",
  [ReasonCodes.Unknown]: "KUI could not refresh this",
};

/** Every known reason, for tests and for exhaustiveness checks over the vocabulary. */
export const AllReasonCodes: readonly KnownReasonCode[] = Object.values(ReasonCodes);

/**
 * The event names every KUI stream uses (ADR-035).
 *
 * `error` is terminal and carries an error envelope, `done` is terminal and carries the continuation
 * cursor on its `id:`, `heartbeat` exists only to stop a proxy from reaping an idle connection, and
 * `phase` reports progress. A stream may add data events of its own; these four are shared by all of
 * them, which is why a caller lists only its own and never these.
 */
export const SseEventNames = {
  Phase: "phase",
  Done: "done",
  Error: "error",
  Heartbeat: "heartbeat",
  Capabilities: "capabilities",
} as const;

/** The names every stream shares, which a caller must not list among its own data events. */
export const SharedSseEventNames: readonly string[] = [
  "phase",
  "done",
  "error",
  "heartbeat",
];

/** The resource names an operator writes in a role, exactly as the server parses them. */
export const Resources = {
  ApplicationConfig: "APPLICATIONCONFIG",
  ClusterConfig: "CLUSTERCONFIG",
  Topic: "TOPIC",
  ConsumerGroup: "CONSUMER",
  Schema: "SCHEMA",
  Connect: "CONNECT",
  Connector: "CONNECTOR",
  Ksql: "KSQL",
  Acl: "ACL",
  Audit: "AUDIT",
  ClientQuotas: "CLIENT_QUOTAS",
} as const;

/** One resource in the RBAC vocabulary. */
export type ResourceName = (typeof Resources)[keyof typeof Resources];

/** An action, with the resource it belongs to. The pair is the unit, because `VIEW` alone is ambiguous. */
export interface PermissionAction {
  readonly resource: ResourceName;
  readonly action: string;
}

/**
 * Every action the server knows, each carrying its own resource.
 *
 * Pass one of these to the permission store rather than two strings: a mismatched pair — `TOPIC` with
 * `RESET_OFFSETS` — is a question that can only ever answer `false`, and it would answer it silently.
 */
export const Actions = {
  ApplicationConfigView: { resource: "APPLICATIONCONFIG", action: "VIEW" },
  ApplicationConfigEdit: { resource: "APPLICATIONCONFIG", action: "EDIT" },
  ClusterConfigView: { resource: "CLUSTERCONFIG", action: "VIEW" },
  ClusterConfigEdit: { resource: "CLUSTERCONFIG", action: "EDIT" },
  TopicView: { resource: "TOPIC", action: "VIEW" },
  TopicCreate: { resource: "TOPIC", action: "CREATE" },
  TopicEdit: { resource: "TOPIC", action: "EDIT" },
  TopicDelete: { resource: "TOPIC", action: "DELETE" },
  TopicMessagesRead: { resource: "TOPIC", action: "MESSAGES_READ" },
  TopicMessagesProduce: { resource: "TOPIC", action: "MESSAGES_PRODUCE" },
  TopicMessagesDelete: { resource: "TOPIC", action: "MESSAGES_DELETE" },
  TopicAnalysisView: { resource: "TOPIC", action: "ANALYSIS_VIEW" },
  TopicAnalysisRun: { resource: "TOPIC", action: "ANALYSIS_RUN" },
  ConsumerGroupView: { resource: "CONSUMER", action: "VIEW" },
  ConsumerGroupDelete: { resource: "CONSUMER", action: "DELETE" },
  ConsumerGroupResetOffsets: { resource: "CONSUMER", action: "RESET_OFFSETS" },
  SchemaView: { resource: "SCHEMA", action: "VIEW" },
  SchemaCreate: { resource: "SCHEMA", action: "CREATE" },
  SchemaEdit: { resource: "SCHEMA", action: "EDIT" },
  SchemaDelete: { resource: "SCHEMA", action: "DELETE" },
  SchemaModifyGlobalCompatibility: { resource: "SCHEMA", action: "MODIFY_GLOBAL_COMPATIBILITY" },
  ConnectView: { resource: "CONNECT", action: "VIEW" },
  ConnectCreate: { resource: "CONNECT", action: "CREATE" },
  ConnectEdit: { resource: "CONNECT", action: "EDIT" },
  ConnectDelete: { resource: "CONNECT", action: "DELETE" },
  ConnectOperate: { resource: "CONNECT", action: "OPERATE" },
  ConnectResetOffsets: { resource: "CONNECT", action: "RESET_OFFSETS" },
  ConnectorView: { resource: "CONNECTOR", action: "VIEW" },
  ConnectorCreate: { resource: "CONNECTOR", action: "CREATE" },
  ConnectorEdit: { resource: "CONNECTOR", action: "EDIT" },
  ConnectorDelete: { resource: "CONNECTOR", action: "DELETE" },
  ConnectorOperate: { resource: "CONNECTOR", action: "OPERATE" },
  ConnectorResetOffsets: { resource: "CONNECTOR", action: "RESET_OFFSETS" },
  KsqlExecute: { resource: "KSQL", action: "EXECUTE" },
  AclView: { resource: "ACL", action: "VIEW" },
  AclEdit: { resource: "ACL", action: "EDIT" },
  AuditView: { resource: "AUDIT", action: "VIEW" },
  ClientQuotasView: { resource: "CLIENT_QUOTAS", action: "VIEW" },
  ClientQuotasEdit: { resource: "CLIENT_QUOTAS", action: "EDIT" },
} as const satisfies Record<string, PermissionAction>;

/**
 * The connector actions that a permission on the parent connect cluster also grants.
 *
 * Kafbat's rule, which KUI keeps: `EDIT` on the connect cluster `payments` covers all forty of its
 * connectors without a permission naming each one. The fallback uses the *same* action name on
 * `CONNECT`, which the generator asserts, so this is a list rather than a mapping.
 */
export const ConnectorFallbackActions: readonly string[] = [
  "VIEW",
  "CREATE",
  "EDIT",
  "DELETE",
  "OPERATE",
  "RESET_OFFSETS",
];
