// Generated by `./mill frontend.apiConstants` from `kui.contracts.HttpHeaders` and the
// `kui.kernel.error.ErrorCode` enum. Do not edit by hand: your change will be overwritten.

/**
 * The strings the browser and the server must spell identically.
 *
 * `ErrorCodes` is the vocabulary of the error envelope's `code` field (ADR-034). Branch on these
 * constants and never on a message: a message is display text and may be reworded in any release,
 * while a code is a contract and renaming one is a breaking change.
 *
 * A code KUI does not know is still a valid code — a browser built against an older server must
 * render a response from a newer one — so `ErrorCode` is a union of the known names *plus* string,
 * and code that switches on it always needs a default branch.
 */
export const CsrfHeaderName = "X-Csrf-Token" as const;

export const ErrorCodes = {
  /** HTTP 404. No cluster with this id is configured in KUI. */
  ClusterNotFound: "KUI-CLUSTER-NOT-FOUND",
  /** HTTP 409. The configuration changed since it was read; re-read it and apply the change again. */
  ConfigVersionConflict: "KUI-CONFIG-VERSION-CONFLICT",
  /** HTTP 409, retryable. The Kafka Connect cluster is rebalancing and cannot answer yet; retry shortly. */
  ConnectRebalancing: "KUI-CONNECT-REBALANCING",
  /** HTTP 400. The connector offsets in the request are not valid for this connector. */
  ConnectorOffsets: "KUI-CONNECTOR-OFFSETS",
  /** HTTP 400. The paging cursor is past its expiry; start the listing again. */
  CursorExpired: "KUI-CURSOR-EXPIRED",
  /** HTTP 400. The paging cursor is malformed, was not signed by this deployment, or is for another topic. */
  CursorInvalid: "KUI-CURSOR-INVALID",
  /** HTTP 400. The paging cursor exceeds the size limit; narrow the request to fewer partitions. */
  CursorTooLarge: "KUI-CURSOR-TOO-LARGE",
  /** HTTP 400. The smart filter expression could not be compiled. */
  FilterCompile: "KUI-FILTER-COMPILE",
  /** HTTP 403. The authenticated principal does not hold a role that permits this operation. */
  Forbidden: "KUI-FORBIDDEN",
  /** HTTP 409. The consumer group still has members, so its offsets cannot be changed or deleted. */
  GroupNotEmpty: "KUI-GROUP-NOT-EMPTY",
  /** HTTP 404. No consumer group with this id exists on this cluster. */
  GroupNotFound: "KUI-GROUP-NOT-FOUND",
  /** HTTP 500. KUI failed unexpectedly; the correlation id ties this response to the server-side log. */
  Internal: "KUI-INTERNAL",
  /** HTTP 409. The target is not in a state where this operation is allowed. */
  InvalidState: "KUI-INVALID-STATE",
  /** HTTP 405. The cluster is configured read-only, so no operation that changes it is accepted. */
  ReadOnly: "KUI-READ-ONLY",
  /** HTTP 404. No endpoint matches this method and path. */
  RouteNotFound: "KUI-ROUTE-NOT-FOUND",
  /** HTTP 404. The subject or schema version does not exist in the schema registry. */
  SchemaNotFound: "KUI-SCHEMA-NOT-FOUND",
  /** HTTP 503, retryable. The requested serde exists but cannot work right now, usually because its schema registry is unreachable. */
  SerdeUnavailable: "KUI-SERDE-UNAVAILABLE",
  /** HTTP 500. An encrypted field in the metadata store could not be decrypted with any configured key. */
  StoreCrypto: "KUI-STORE-CRYPTO",
  /** HTTP 500. A record in the metadata store is not a readable envelope for this version of KUI. */
  StoreEnvelope: "KUI-STORE-ENVELOPE",
  /** HTTP 501. No metadata store is configured, so this change cannot be persisted; configure kui.store.kafka.* to enable it. */
  StoreNotConfigured: "KUI-STORE-NOT-CONFIGURED",
  /** HTTP 503, retryable. The metadata store's log could not be replayed to its end within the configured timeout. */
  StoreReplayTimeout: "KUI-STORE-REPLAY-TIMEOUT",
  /** HTTP 500. An existing metadata-store topic has settings KUI cannot use, and KUI never rewrites an existing topic's configuration. */
  StoreTopicIncompatible: "KUI-STORE-TOPIC-INCOMPATIBLE",
  /** HTTP 503, retryable. KUI's metadata store could not be reached; reads are served from the last replayed state and writes are rejected. */
  StoreUnavailable: "KUI-STORE-UNAVAILABLE",
  /** HTTP 408, retryable. The operation did not finish inside its time budget. */
  Timeout: "KUI-TIMEOUT",
  /** HTTP 404. The topic does not exist on this cluster. */
  TopicNotFound: "KUI-TOPIC-NOT-FOUND",
  /** HTTP 401. The request carried no valid identity; sign in, or check the signed principal header. */
  Unauthenticated: "KUI-UNAUTHENTICATED",
  /** HTTP 501. This cluster or upstream does not support the requested feature. */
  Unsupported: "KUI-UNSUPPORTED",
  /** HTTP 502. KUI's credentials for the upstream system were rejected; the configuration needs fixing. */
  UpstreamAuth: "KUI-UPSTREAM-AUTH",
  /** HTTP 502, retryable. ksqlDB answered with an error or an unusable response. */
  UpstreamKsql: "KUI-UPSTREAM-KSQL",
  /** HTTP 503, retryable. The upstream system could not be reached, or its circuit breaker is open. */
  UpstreamUnavailable: "KUI-UPSTREAM-UNAVAILABLE",
  /** HTTP 400. The request is not valid; the details array names each field and what it must satisfy. */
  Validation: "KUI-VALIDATION",
} as const;

/** One of the codes this build knows about. */
export type KnownErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/**
 * Any code an envelope can carry. The `(string & {})` arm keeps a code from a newer server
 * decodable while still offering the known names to autocompletion.
 */
// eslint-disable-next-line @typescript-eslint/ban-types
export type ErrorCode = KnownErrorCode | (string & {});

/** Every known code, for tests and for exhaustiveness checks over the vocabulary. */
export const AllErrorCodes: readonly KnownErrorCode[] = Object.values(ErrorCodes);
