package kui.cluster.domain

import scala.concurrent.duration.FiniteDuration

/** How much of a stated window this cluster had an active controller.
  *
  * ==Why a window and not an instant==
  *
  * Every other figure on `ClusterTopology` is a fact about one scrape. This one is not: "99.72 %" is a
  * statement about a period, and the period has to be carried with it or the number means nothing. A
  * percentage computed over the four minutes since the process booted and printed as "over the last 6h" is
  * the failure `SeriesWindow` in `libs/cache` was built to make impossible, and this figure refuses the same
  * way — `percent` is `None` until the window has actually been collecting for `window`.
  *
  * `coverage` is carried alongside so that the refusal can be explained rather than merely shown: a client
  * that got `None` can say "collecting, 41m of 6h" instead of drawing an empty ring, which is the difference
  * between a KUI that has just started and one that cannot measure this at all.
  *
  * ==What this type does not tell a client, and why==
  *
  * There are two refusals here and a third case that is neither. A window that has spanned its whole six
  * hours and was successfully scraped *twice* answers `percent 100.0, window 21600, coverage 21600` — byte
  * for byte what a window with all 360 observations answers. That is deliberate and
  * `aGapIsNotACountedAbsence` asserts the half of it that matters: a scrape KUI could not make records
  * nothing, because KUI being unable to ask is not the cluster being without a controller, and 358 minutes of
  * `false` would report KUI's own outage as the cluster's.
  *
  * The cost is that no client can tell a percentage over two samples from one over 360 while being told it is
  * "over the last 6h". Carrying the observation count would close that, and it is not being carried:
  * `ControllerUptimeDto` is a published wire shape whose goldens live in four places and whose merged OpenAPI
  * documents are regenerated by a different packet, so a field added for a case this rare would be a shape
  * change made for a footnote. `aSparseWindowIsIndistinguishableFromAFullOne` pins the consequence, so that
  * filling the gap later is a deliberate deletion rather than a discovery. Until then the honest reading of
  * this document is "of the scrapes that landed, this share found a controller", and `coverage` says how long
  * the window has been open, not how densely it was filled.
  *
  * @param window
  *   the period the percentage is over. It travels to the browser so that the label reads "over the last 6h"
  *   from data rather than from a literal that would go stale the day the window is retuned
  * @param coverage
  *   how long the window has been collecting, capped by its own retention. Never longer than `window` in any
  *   value this service produces, because the window is what it is capped at
  * @param percent
  *   the share of the observed samples in which a controller was present, to two decimals. `None` when the
  *   window does not yet span `window`, and also when it spans it having observed nothing at all — a
  *   percentage over no observations is not a percentage, whatever shape the buckets came back in
  */
final case class ControllerUptime(
    window: FiniteDuration,
    coverage: FiniteDuration,
    percent: Option[Double]
)

object ControllerUptime {

  /** Folds the samples a window answered with into a percentage, or refuses.
    *
    * `observations` is `None` when the window declined to answer at all — it has not been collecting for
    * `window` — and `Some(empty)` when it answered with nothing but gaps, which is what a cluster KUI has
    * been unable to reach for the whole window looks like. Both are `None` here, and they are kept apart at
    * the call site by `coverage`, not by inventing a figure for either.
    *
    * A sample is `true` when that scrape found a controller. A scrape that failed records **nothing** rather
    * than `false`: KUI being unable to ask is not the cluster being without a controller, and a gap says so
    * where a zero would not.
    */
  def of(
      window: FiniteDuration,
      coverage: FiniteDuration,
      observations: Option[Vector[Boolean]]
  ): ControllerUptime =
    ControllerUptime(
      window = window,
      coverage = coverage,
      percent = observations.filter(_.nonEmpty).map { samples =>
        percentage(samples.count(identity), samples.size)
      }
    )

  /** Two decimals, rounded here so that a client rounding it again would not be a second rounding rule for
    * one number.
    *
    * ==What the shipped window can actually produce==
    *
    * `ClusterBootstrap` keeps a 6 h window at a 1 min step, so the fold sees at most 360 observations and the
    * only percentages reachable are `k / 360`: `100.00`, then `99.72`, then `99.44`. The worked example this
    * repository printed until 2026-09-06 — `99.98 %`, in four scaladocs, two suites and a golden document
    * with its Scala twin — sits between the first two, and no deployment of KUI could ever emit it. The
    * example is now `99.72`: one missed minute out of the 360.
    *
    * Two decimals is nevertheless the precision, and that is the decision rather than an oversight. At 360
    * buckets one decimal would already separate every reachable reading, so the second digit buys nothing
    * *today*; the window and the step are two constants an operator-facing tuning change can move, and at 24
    * h over the same 1 min step the reachable values are 0.069 apart, where one decimal would silently merge
    * two different readings. The precision is chosen for the finest grid the constants permit, and the cost
    * of carrying it at a coarser one is a trailing zero.
    */
  private def percentage(present: Int, observed: Int): Double =
    math.round(present.toDouble / observed.toDouble * 100.0d * 100.0d).toDouble / 100.0d

  given CanEqual[ControllerUptime, ControllerUptime] = CanEqual.derived
}
