package kui.tools

import kui.contracts.HttpHeaders
import kui.contracts.capability.{CapabilityState, DegradedReason, ReasonCode}
import kui.contracts.sse.SseEventName
import kui.security.rbac.{Action, Resource}
import kui.kernel.error.ErrorCode

/** Renders the handful of strings the browser and the server must spell identically, as TypeScript.
  *
  * ==Why this file is generated rather than written==
  *
  * Two of these strings have already caused shipped defects, and both defects had the same shape: one side
  * was changed and the other was not, and nothing failed until a user tried something.
  *
  *   - The CSRF header name. `HttpHeaders.Csrf` explains what happened -- the browser sent `X-Kui-Csrf` while
  *     the gateway read `X-Csrf-Token`, so every mutation came back `403` -- and the fix was to put the name
  *     in one place both halves compile against. Under ADR-011 "both halves" meant Scala.js; under ADR-048
  *     the browser is TypeScript and cannot compile against a Scala object, so the constant is *emitted* into
  *     one instead, checked by the build exactly like the OpenAPI documents are.
  *   - The error codes. ADR-034 makes `code` the stable thing a browser switches on, and the UI is required
  *     to render by code rather than by message. A UI that switches on a code the server has renamed silently
  *     falls through to its default branch, which is the "unexpected error" panel -- the failure looks like a
  *     server bug and is a client bug.
  *
  * The generated file is committed and `--check`ed, so renaming a code without regenerating fails CI, and
  * regenerating it fails `tsc` at every browser branch that still names the old one.
  *
  * ==What is deliberately *not* generated==
  *
  * The response shapes. Those come from `docs/api/openapi.browser.json` through `openapi-typescript` (ADR-048
  * §3), which is a far better source than anything hand-rolled here. This file covers only the strings that
  * never appear in an OpenAPI document at all: a header's name and the vocabulary of `code`.
  */
object BrowserConstants {

  /** The line that tells a reader not to edit the file, and how to regenerate it. */
  val GeneratedWarning: String =
    "// Generated by `./mill frontend.apiConstants` from `kui.contracts.HttpHeaders` and the\n" +
      "// `kui.kernel.error.ErrorCode` and `kui.contracts.capability.ReasonCode` enums, the\n" +
      "// `kui.contracts.sse.SseEventName` constants and the `kui.security.rbac` vocabulary. Do not\n" +
      "// edit by hand: your change will be overwritten."

  def render(codes: List[ErrorCode]): String = {
    val sorted = codes.sortBy(_.wire)

    val entries = sorted.map { code =>
      s"""  /** HTTP ${code.httpStatus}${if code.retryable then ", retryable" else ""}. ${code.description} */
         |  ${identifier(code)}: "${code.wire}",""".stripMargin
    }

    (List(
      GeneratedWarning,
      "",
      "/**",
      " * The strings the browser and the server must spell identically.",
      " *",
      " * `ErrorCodes` is the vocabulary of the error envelope's `code` field (ADR-034). Branch on these",
      " * constants and never on a message: a message is display text and may be reworded in any release,",
      " * while a code is a contract and renaming one is a breaking change.",
      " *",
      " * A code KUI does not know is still a valid code — a browser built against an older server must",
      " * render a response from a newer one — so `ErrorCode` is a union of the known names *plus* string,",
      " * and code that switches on it always needs a default branch.",
      " */",
      "export const CsrfHeaderName = " + quoted(HttpHeaders.Csrf) + " as const;",
      "",
      "export const ErrorCodes = {"
    ) ++ entries ++ List(
      "} as const;",
      "",
      "/** One of the codes this build knows about. */",
      "export type KnownErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];",
      "",
      "/**",
      " * Any code an envelope can carry. The `(string & {})` arm keeps a code from a newer server",
      " * decodable while still offering the known names to autocompletion.",
      " */",
      "// eslint-disable-next-line @typescript-eslint/ban-types",
      "export type ErrorCode = KnownErrorCode | (string & {});",
      "",
      "/** Every known code, for tests and for exhaustiveness checks over the vocabulary. */",
      "export const AllErrorCodes: readonly KnownErrorCode[] = Object.values(ErrorCodes);",
      ""
    ) ++ capabilitySection ++ streamEvents ++ vocabulary).mkString("\n") + "\n"
  }

  /** The capability vocabulary: the `status` discriminator, the reason codes, and their sentences.
    *
    * The sentences come across as well as the codes, and that is the point of generating this rather than
    * writing it. `ReasonCode.sentence` is already the reviewed wording -- "the cluster is not answering",
    * never "UPSTREAM_UNAVAILABLE" -- and it is what the sidebar tooltip, the fallback panel and the cluster
    * switcher all show. Copied into TypeScript by hand, the three would drift from the Scala and from each
    * other, which is the exact failure `Messages.scala` existed to prevent under the previous frontend.
    */
  private def capabilitySection: List[String] = {
    val statuses = List(
      CapabilityState.Available,
      CapabilityState.Degraded(DegradedPlaceholder),
      CapabilityState.Unavailable(ReasonCode.Unknown, "", java.time.Instant.EPOCH),
      CapabilityState.NotConfigured
    )

    val statusEntries = statuses.map { state =>
      s"""  ${state.productPrefix}: ${quoted(state.status)},"""
    }

    val reasonEntries = ReasonCode.values.toList.map { code =>
      s"""  /** ${code.sentence.capitalize}. */
         |  ${code.productPrefix}: ${quoted(code.wire)},""".stripMargin
    }

    val sentenceEntries = ReasonCode.values.toList.map { code =>
      s"""  [ReasonCodes.${code.productPrefix}]: ${quoted(code.sentence)},"""
    }

    List(
      "/**",
      " * The four values of a capability's `status` field (ADR-032).",
      " *",
      " * This field is the discriminator the wire carries and the OpenAPI document does not describe, so it",
      " * is the one part of a capability frame a hand-written decoder has to read. See",
      " * `kui.contracts.capability.CapabilityState`, whose Circe codec writes it.",
      " */",
      "export const CapabilityStatuses = {"
    ) ++ statusEntries ++ List(
      "} as const;",
      "",
      "export type CapabilityStatus = (typeof CapabilityStatuses)[keyof typeof CapabilityStatuses];",
      "",
      "/**",
      " * Why a capability is not fully available.",
      " *",
      " * As with `ErrorCode`, a reason a newer gateway invents must not stop an older browser reading the",
      " * frame: anything unrecognised decodes to `Unknown` rather than failing.",
      " */",
      "export const ReasonCodes = {"
    ) ++ reasonEntries ++ List(
      "} as const;",
      "",
      "export type KnownReasonCode = (typeof ReasonCodes)[keyof typeof ReasonCodes];",
      "",
      "/**",
      " * The sentence to show a person for each reason, as reviewed on the server.",
      " *",
      " * Written about KUI's relationship with the cluster rather than about HTTP: \"the cluster is not",
      " * answering\" is something an operator can go and check, where \"kafka answered with status 502\" names",
      " * a status no broker can return.",
      " */",
      "export const ReasonSentences: Readonly<Record<KnownReasonCode, string>> = {"
    ) ++ sentenceEntries ++ List(
      "};",
      "",
      "/** Every known reason, for tests and for exhaustiveness checks over the vocabulary. */",
      "export const AllReasonCodes: readonly KnownReasonCode[] = Object.values(ReasonCodes);"
    )
  }

  /** Only ever used to reach `CapabilityState.Degraded`'s `status` string; none of its fields is rendered. */
  private val DegradedPlaceholder: DegradedReason =
    DegradedReason(ReasonCode.Unknown, "", None, None)


  /** The `event:` names of ADR-035, so a browser listener and a server writer cannot be renamed apart.
    *
    * They belong here for exactly the reason the CSRF header does: an OpenAPI document describes request and
    * response *bodies*, and a stream's event names appear in neither. A browser listening for `hearbeat`
    * would compile, run, and quietly treat every keep-alive as an unknown event.
    */
  private def streamEvents: List[String] = List(
    "",
    "/**",
    " * The event names every KUI stream uses (ADR-035).",
    " *",
    " * `error` is terminal and carries an error envelope, `done` is terminal and carries the continuation",
    " * cursor on its `id:`, `heartbeat` exists only to stop a proxy from reaping an idle connection, and",
    " * `phase` reports progress. A stream may add data events of its own; these four are shared by all of",
    " * them, which is why a caller lists only its own and never these.",
    " */",
    "export const SseEventNames = {",
    s"  Phase: ${quoted(SseEventName.Phase)},",
    s"  Done: ${quoted(SseEventName.Done)},",
    s"  Error: ${quoted(SseEventName.Error)},",
    s"  Heartbeat: ${quoted(SseEventName.Heartbeat)},",
    s"  Capabilities: ${quoted(SseEventName.Capabilities)},",
    "} as const;",
    "",
    "/** The names every stream shares, which a caller must not list among its own data events. */",
    "export const SharedSseEventNames: readonly string[] = [",
    SseEventName.shared.map(name => s"  ${quoted(name)},").mkString("\n"),
    "];"
  )

  /** The RBAC vocabulary, as the browser's permission store needs it.
    *
    * ==Why an action carries its resource==
    *
    * The wire spelling of an action is not unique: `VIEW` is eleven different actions on eleven different
    * resources, and `Action.fromWire` on the server takes a resource for precisely that reason. A browser
    * that passed a bare `"VIEW"` to a permission check would be asking a question with no answer, so each
    * entry here is the pair the Scala enum already is — a resource and an action name together.
    *
    * ==Why it is generated==
    *
    * These strings are an operator's configuration file. They appear in an OpenAPI document only as
    * `resource: string` and `actions: string[]`, so nothing would fail if the browser asked for `CONSUMER`
    * after the server had renamed it — every write control on the consumer screen would simply go quiet, and
    * a disabled button looks exactly like a permission the user does not hold.
    */
  private def vocabulary: List[String] = {
    val resources = Resource.values.toList.map { resource =>
      s"  ${resource.toString}: ${quoted(resource.wire)},"
    }

    val actions = Action.values.toList.map { action =>
      s"  ${action.toString}: { resource: ${quoted(action.resource.wire)}, " +
        s"action: ${quoted(action.wire)} }," 
    }

    // Every connector action falls back to the *same-named* action on the parent connect cluster, so
    // what the browser needs is the list of actions that have a fallback at all, not a mapping. The
    // assertion is here rather than in a comment: if a future action ever maps to a differently-named
    // parent, this generator fails and the browser's evaluator is corrected with it.
    val mismatched = Action.values.toList.flatMap { action =>
      action.onParentConnect.filter(_.wire != action.wire).map(parent => s"${action.wire} -> ${parent.wire}")
    }

    if mismatched.nonEmpty then
      throw new IllegalStateException(
        "a connector action no longer falls back to the same-named connect action: " +
          mismatched.mkString(", ") +
          ". The browser's permission evaluator assumes the names match; fix both together."
      )

    val parents = Action.values.toList
      .filter(_.onParentConnect.isDefined)
      .map(action => s"  ${quoted(action.wire)},")

    List(
      "",
      "/** The resource names an operator writes in a role, exactly as the server parses them. */",
      "export const Resources = {"
    ) ++ resources ++ List(
      "} as const;",
      "",
      "/** One resource in the RBAC vocabulary. */",
      "export type ResourceName = (typeof Resources)[keyof typeof Resources];",
      "",
      "/** An action, with the resource it belongs to. The pair is the unit, because `VIEW` alone is ambiguous. */",
      "export interface PermissionAction {",
      "  readonly resource: ResourceName;",
      "  readonly action: string;",
      "}",
      "",
      "/**",
      " * Every action the server knows, each carrying its own resource.",
      " *",
      " * Pass one of these to the permission store rather than two strings: a mismatched pair — `TOPIC` with",
      " * `RESET_OFFSETS` — is a question that can only ever answer `false`, and it would answer it silently.",
      " */",
      "export const Actions = {"
    ) ++ actions ++ List(
      "} as const satisfies Record<string, PermissionAction>;",
      "",
      "/**",
      " * The connector actions that a permission on the parent connect cluster also grants.",
      " *",
      " * Kafbat's rule, which KUI keeps: `EDIT` on the connect cluster `payments` covers all forty of its",
      " * connectors without a permission naming each one. The fallback uses the *same* action name on",
      " * `CONNECT`, which the generator asserts, so this is a list rather than a mapping.",
      " */",
      "export const ConnectorFallbackActions: readonly string[] = ["
    ) ++ parents ++ List("];")
  }

  private def quoted(value: String): String = "\"" + value + "\""

  /** `KUI-TOPIC-NOT-FOUND` becomes `TopicNotFound`: the enum case's own name, rebuilt from the wire string.
    *
    * Rebuilt rather than read off `ErrorCode` because Scala 3's `productPrefix` is the case name and would
    * make the TypeScript identifier depend on a Scala identifier that carries no contract. The wire string is
    * the contract, so the TypeScript name is derived from it and changes when it does.
    */
  private def identifier(code: ErrorCode): String =
    code.wire
      .stripPrefix("KUI-")
      .split('-')
      .map(part => part.take(1) + part.drop(1).toLowerCase)
      .mkString
}
