package kui.tools

import kui.contracts.HttpHeaders
import kui.kernel.error.ErrorCode

/** Renders the handful of strings the browser and the server must spell identically, as TypeScript.
  *
  * ==Why this file is generated rather than written==
  *
  * Two of these strings have already caused shipped defects, and both defects had the same shape: one side
  * was changed and the other was not, and nothing failed until a user tried something.
  *
  *   - The CSRF header name. `HttpHeaders.Csrf` explains what happened -- the browser sent `X-Kui-Csrf` while
  *     the gateway read `X-Csrf-Token`, so every mutation came back `403` -- and the fix was to put the name
  *     in one place both halves compile against. Under ADR-011 "both halves" meant Scala.js; under ADR-048
  *     the browser is TypeScript and cannot compile against a Scala object, so the constant is *emitted* into
  *     one instead, checked by the build exactly like the OpenAPI documents are.
  *   - The error codes. ADR-034 makes `code` the stable thing a browser switches on, and the UI is required
  *     to render by code rather than by message. A UI that switches on a code the server has renamed silently
  *     falls through to its default branch, which is the "unexpected error" panel -- the failure looks like a
  *     server bug and is a client bug.
  *
  * The generated file is committed and `--check`ed, so renaming a code without regenerating fails CI, and
  * regenerating it fails `tsc` at every browser branch that still names the old one.
  *
  * ==What is deliberately *not* generated==
  *
  * The response shapes. Those come from `docs/api/openapi.browser.json` through `openapi-typescript` (ADR-048
  * §3), which is a far better source than anything hand-rolled here. This file covers only the strings that
  * never appear in an OpenAPI document at all: a header's name and the vocabulary of `code`.
  */
object BrowserConstants {

  /** The line that tells a reader not to edit the file, and how to regenerate it. */
  val GeneratedWarning: String =
    "// Generated by `./mill frontend.apiConstants` from `kui.contracts.HttpHeaders` and the\n" +
      "// `kui.kernel.error.ErrorCode` enum. Do not edit by hand: your change will be overwritten."

  def render(codes: List[ErrorCode]): String = {
    val sorted = codes.sortBy(_.wire)

    val entries = sorted.map { code =>
      s"""  /** HTTP ${code.httpStatus}${if code.retryable then ", retryable" else ""}. ${code.description} */
         |  ${identifier(code)}: "${code.wire}",""".stripMargin
    }

    (List(
      GeneratedWarning,
      "",
      "/**",
      " * The strings the browser and the server must spell identically.",
      " *",
      " * `ErrorCodes` is the vocabulary of the error envelope's `code` field (ADR-034). Branch on these",
      " * constants and never on a message: a message is display text and may be reworded in any release,",
      " * while a code is a contract and renaming one is a breaking change.",
      " *",
      " * A code KUI does not know is still a valid code — a browser built against an older server must",
      " * render a response from a newer one — so `ErrorCode` is a union of the known names *plus* string,",
      " * and code that switches on it always needs a default branch.",
      " */",
      "export const CsrfHeaderName = " + quoted(HttpHeaders.Csrf) + " as const;",
      "",
      "export const ErrorCodes = {"
    ) ++ entries ++ List(
      "} as const;",
      "",
      "/** One of the codes this build knows about. */",
      "export type KnownErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];",
      "",
      "/**",
      " * Any code an envelope can carry. The `(string & {})` arm keeps a code from a newer server",
      " * decodable while still offering the known names to autocompletion.",
      " */",
      "// eslint-disable-next-line @typescript-eslint/ban-types",
      "export type ErrorCode = KnownErrorCode | (string & {});",
      "",
      "/** Every known code, for tests and for exhaustiveness checks over the vocabulary. */",
      "export const AllErrorCodes: readonly KnownErrorCode[] = Object.values(ErrorCodes);"
    )).mkString("\n") + "\n"
  }

  private def quoted(value: String): String = "\"" + value + "\""

  /** `KUI-TOPIC-NOT-FOUND` becomes `TopicNotFound`: the enum case's own name, rebuilt from the wire string.
    *
    * Rebuilt rather than read off `ErrorCode` because Scala 3's `productPrefix` is the case name and would
    * make the TypeScript identifier depend on a Scala identifier that carries no contract. The wire string is
    * the contract, so the TypeScript name is derived from it and changes when it does.
    */
  private def identifier(code: ErrorCode): String =
    code.wire
      .stripPrefix("KUI-")
      .split('-')
      .map(part => part.take(1) + part.drop(1).toLowerCase)
      .mkString
}
