package kui.tools

import kui.kernel.error.ErrorCode

/** Renders the operator-facing error-code table from the enum that defines it.
  *
  * The document exists because an operator who sees `KUI-UPSTREAM-UNAVAILABLE` in a log line needs one page
  * to look it up in, and that page is only useful if it is complete. A hand-maintained table is complete on
  * the day it is written and wrong a month later, so this one is generated: every case of `ErrorCode` carries
  * its own description (ADR-034 amendment 2), the compiler refuses a case that has none, and
  * `./mill docs.errorCodes --check` fails the build when the committed file no longer matches the enum.
  *
  * The rendering is a pure function so it can be tested against an exact expected string; the Mill task only
  * decides where to write the result.
  */
object ErrorCodeDoc {

  /** The line that tells a reader not to edit the file, and how to regenerate it. */
  val GeneratedWarning: String =
    "<!-- Generated by `./mill docs.errorCodes` from the ErrorCode enum in libs/kernel. " +
      "Do not edit by hand: your change will be overwritten. -->"

  def render(codes: List[ErrorCode]): String = {
    val rows = codes.sortBy(_.wire).map(row)

    (List(
      GeneratedWarning,
      "",
      "# Error codes",
      "",
      "Every KUI failure carries one of these codes in the `code` field of the error envelope",
      "(ADR-034). The code is stable: it is what a log query and a browser switch on, so renaming",
      "one is a breaking change. `Retryable` means the same request, unchanged, could succeed later.",
      "",
      "| Code | HTTP | Retryable | Area | Meaning |",
      "| --- | --- | --- | --- | --- |"
    ) ++ rows).mkString("\n") + "\n"
  }

  private def row(code: ErrorCode): String =
    s"| `${code.wire}` | ${code.httpStatus} | ${if code.retryable then "yes" else "no"} | " +
      s"${code.area} | ${code.description} |"
}
